### ISSUE TITLE
how to change theme/color of calendar

### ISSUE THREAD

**Issue by adamelmohamad** [aryella-lacerda/react-native-easy-calendar#6]
Hi guys, I want to change the colour from the calendar's theme from green to purple. How would I go about this?

![image](https://user-images.githubusercontent.com/37544116/100556196-afeebd80-32f4-11eb-8474-8b721727f05b.png)

**Comment by aryella-lacerda** [comment]
Hello, @adamelmohamad! That green color is the [Light Themes](https://github.com/aryella-lacerda/react-native-easy-calendar/blob/master/src/Themes/DefaultTheme.ts)'s **primary** color. It should be sufficient to override the styles where this color appears:

- selectedMonthText
- selectedDay
- normalArrowImage

```jsx
import { DateSelectionCalendar, DefaultTheme, Theme } from 'react-native-easy-calendar';

const ThemedCalendar = () => {
  const [selectedDate, setSelectedDate] = React.useState('2020-02-01');

  return (
    <DateSelectionCalendar
      theme={CustomTheme}
      onSelectDate={setSelectedDate}
      selectedDate={selectedDate}
    />
  );
};

const CustomTheme: Theme = {
  ...DefaultTheme,
  selectedMonthText: {
    color: 'purple',
  },
  selectedDay: {
    ...DefaultTheme.selectedDay,
    backgroundColor: 'purple',
  },
  normalArrowImage: {
    ...DefaultTheme.normalArrowImage,
    tintColor: 'purple',
  }
};
```

**Comment by aryella-lacerda** [comment]
Closing inactive thread ✌🏼

**Comment by fio-la** [comment]
How can I do this without TypeScript? 
Thank you
