### ISSUE TITLE
How to use mark an array of Dates without Typescript 

### ISSUE THREAD

**Issue by fio-la** [aryella-lacerda/react-native-easy-calendar#7]
Hello,

I have this Code and I when I enter the Calender on the first view allDates[] should me marked in the Calender. Is this somehow possible without Typescript? Because I get the error "TypeError: Cannot read property 'reduce' of undefined". I do not know if this is somehow related to me not using typescript but only react natvie. Thanks for your help.

```
import {  MultiDateSelectionCalendar, DefaultTheme } from 'react-native-easy-calendar'
import germanLocale from 'dayjs/locale/de';
import React from 'react';


var allDates=[""];

export default class Kalender extends React.Component {

  render(){
  
  const {date} = this.props.route.params;
  allDates.push(date.toString());
  console.log("type of variable is:"+typeof(date));

  return (
    < MultiDateSelectionCalendar
  
      disabledDates={['2021-01-02', '2021-12-31']}

      initVisibleDate={'2021-02-10'} 
      minDate={'2021-01-10'}
      maxDate={'2021-04-10'}
      allowYearView={true}
      showExtraDates={false}
      testID={'my-calendar-component'}
      locale={germanLocale} 
      theme={DefaultTheme}
      onSelectDate={allDates}
      selectedDate={allDates}
    />
  );
};
}
```

**Comment by aryella-lacerda** [comment]
Hello, @fi-cyber! 😁 There are actually two problems here. 

1) The `MultiDateSelectionCalendar` receives the props `onSelectDates` and `selectedDates` (plural, not singular). If you correct this, the first error should disappear. 

2) The `onSelectDates` prop receives a function, not an array. Correcting that should make the second error disappear as well.

It's totally possible to use this lib without Typescript, but it's true that the errors for missing required props could be clearer. 🤔 I'll take a look and throw some more readable errors. ✌🏼

**Comment by fio-la** [comment]
Thanks a lot for the information and your engagement.
